server {
  listen 80;

  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Soporte de rutas SPA de Vite/React
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Rutas para cada subapp
  location /appointments/ {
    alias /usr/share/nginx/html/appointments/;
    try_files $uri $uri/ /appointments/index.html;
  }

  location /doctors/ {
    alias /usr/share/nginx/html/doctors/;
    try_files $uri $uri/ /doctors/index.html;
  }

  location /patients/ {
    alias /usr/share/nginx/html/patients/;
    try_files $uri $uri/ /patients/index.html;
  }

  location /pharmacy/ {
    alias /usr/share/nginx/html/pharmacy/;
    try_files $uri $uri/ /pharmacy/index.html;
  }

  error_page 404 /index.html;
}
